# Copyright 2011 Petar Maymounkov. All rights reserved.
# Use of this source code is governed by a GPL-style
# license that can be found in the LICENSE file.

include $(GOROOT)/src/Make.inc

TARG=faff
GOFILES=\
	fs.go\
	main.go\
	post.go\
	index.go\
	cached.go\
	git.go\
	site.go\
	page.go\

include $(GOROOT)/src/Make.cmd
